repo:
    - ./*

ci:
    - any: [".github/**/*"]

test:
    - source/**/*.test.ts

"Domain: SDK":
    - packages/sdk/*
    - packages/sdk/**/*

"Domain: ADA":
    - packages/sdk-ada/*
    - packages/sdk-ada/**/*

"Domain: ARK":
    - packages/sdk-ark/*
    - packages/sdk-ark/**/*

"Domain: ATOM":
    - packages/sdk-atom/*
    - packages/sdk-atom/**/*

"Domain: AVAX":
    - packages/sdk-avax/*
    - packages/sdk-avax/**/*

"Domain: BTC":
    - packages/sdk-btc/*
    - packages/sdk-btc/**/*

"Domain: DOT":
    - packages/sdk-dot/*
    - packages/sdk-dot/**/*

"Domain: EGLD":
    - packages/sdk-egld/*
    - packages/sdk-egld/**/*

"Domain: EOS":
    - packages/sdk-eos/*
    - packages/sdk-eos/**/*

"Domain: ETH":
    - packages/sdk-eth/*
    - packages/sdk-eth/**/*

"Domain: INTL":
    - packages/sdk-intl/*
    - packages/sdk-intl/**/*

"Domain: LSK":
    - packages/sdk-lsk/*
    - packages/sdk-lsk/**/*

"Domain: NEO":
    - packages/sdk-neo/*
    - packages/sdk-neo/**/*

"Domain: SOL":
    - packages/sdk-sol/*
    - packages/sdk-sol/**/*

"Domain: TRX":
    - packages/sdk-trx/*
    - packages/sdk-trx/**/*

"Domain: XLM":
    - packages/sdk-xlm/*
    - packages/sdk-xlm/**/*

"Domain: XRP":
    - packages/sdk-xrp/*
    - packages/sdk-xrp/**/*

"Domain: ZIL":
    - packages/sdk-zil/*
    - packages/sdk-zil/**/*
