repo:
    - ./*

ci:
    - any: [".github/**/*"]

test:
    - source/**/*.test.ts

"Domain: SDK":
    - packages/sdk/*
    - packages/sdk/**/*

"Domain: ADA":
    - packages/sdk-ada/*
    - packages/sdk-ada/**/*

"Domain: ARK":
    - packages/sdk-ark/*
    - packages/sdk-ark/**/*

"Domain: ATOM":
    - packages/sdk-atom/*
    - packages/sdk-atom/**/*

"Domain: AVAX":
    - packages/sdk-avax/*
    - packages/sdk-avax/**/*

"Domain: BTC":
    - packages/sdk-btc/*
    - packages/sdk-btc/**/*

"Domain: CLI":
    - packages/sdk-cli/*
    - packages/sdk-cli/**/*

"Domain: Crypto":
    - packages/sdk-crypto/*
    - packages/sdk-crypto/**/*

"Domain: DOT":
    - packages/sdk-dot/*
    - packages/sdk-dot/**/*

"Domain: EGLD":
    - packages/sdk-egld/*
    - packages/sdk-egld/**/*

"Domain: EOS":
    - packages/sdk-eos/*
    - packages/sdk-eos/**/*

"Domain: ETH":
    - packages/sdk-eth/*
    - packages/sdk-eth/**/*

"Domain: HTTP/axios":
    - packages/sdk-http-axios/*
    - packages/sdk-http-axios/**/*

"Domain: HTTP/bent":
    - packages/sdk-http-bent/*
    - packages/sdk-http-bent/**/*

"Domain: HTTP/got":
    - packages/sdk-http-got/*
    - packages/sdk-http-got/**/*

"Domain: HTTP/ky":
    - packages/sdk-http-ky/*
    - packages/sdk-http-ky/**/*

"Domain: HTTP/node-fetch":
    - packages/sdk-http-node-fetch/*
    - packages/sdk-http-node-fetch/**/*

"Domain: INTL":
    - packages/sdk-intl/*
    - packages/sdk-intl/**/*

"Domain: LSK":
    - packages/sdk-lsk/*
    - packages/sdk-lsk/**/*

"Domain: Markets":
    - packages/sdk-markets/*
    - packages/sdk-markets/**/*

"Domain: NEO":
    - packages/sdk-neo/*
    - packages/sdk-neo/**/*

"Domain: News":
    - packages/sdk-news/*
    - packages/sdk-news/**/*

"Domain: Profiles":
    - packages/sdk-profiles/*
    - packages/sdk-profiles/**/*

"Domain: SOL":
    - packages/sdk-sol/*
    - packages/sdk-sol/**/*

"Domain: JSPN-RPC":
    - packages/sdk-json-rpc/*
    - packages/sdk-json-rpc/**/*

"Domain: Support":
    - packages/sdk-support/*
    - packages/sdk-support/**/*

"Domain: TRX":
    - packages/sdk-trx/*
    - packages/sdk-trx/**/*

"Domain: XLM":
    - packages/sdk-xlm/*
    - packages/sdk-xlm/**/*

"Domain: XRP":
    - packages/sdk-xrp/*
    - packages/sdk-xrp/**/*

"Domain: ZIL":
    - packages/sdk-zil/*
    - packages/sdk-zil/**/*
